security.protocol=SASL_SSL
sasl.mechanism=OAUTHBEARER
sasl.oauthbearer.token.endpoint.url=https://keycloak.appf4.io.vn/realms/jhipster/protocol/openid-connect/token

ssl.truststore.location=/etc/kafka/secrets/kafka.client.truststore.jks
ssl.truststore.password=f4security
ssl.endpoint.identification.algorithm=

sasl.login.callback.handler.class=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginCallbackHandler

sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
  clientId='svc-admin-bootstrap' \
  clientSecret='EB4eohc7BEY3tw1Rjg7FS8xMLfi95n0n' \
  scope='profile email' \
  tokenEndpointUrl='https://keycloak.appf4.io.vn/realms/jhipster/protocol/openid-connect/token';
